#!/bin/bash
set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

function print_header() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

function print_success() {
    echo -e "${GREEN}SUCCESS: $1${NC}"
}

function check_command() {
    if ! command -v $1 &> /dev/null; then
        echo "Error: $1 is not installed."
        exit 1
    fi
}

function dev() {
    print_header "Starting Local Development Stack"

    check_command docker

    # Determine which docker compose command to use
    # Determine which docker compose command to use
    if docker compose version &> /dev/null; then
        DOCKER_COMPOSE_CMD="docker compose"
        echo "Using Docker Compose V2 (Plugin)"
    elif command -v docker-compose &> /dev/null; then
        DOCKER_COMPOSE_CMD="docker-compose"
        echo "Using Docker Compose V1 (Legacy)"
    else
        echo "Error: docker-compose is not installed."
        exit 1
    fi

    if [ ! -f .env ]; then
        if [ -f .env.example ]; then
            echo "Creating .env file from .env.example..."
            cp .env.example .env
        else
            echo "Creating .env file with defaults..."
            # Generate some random secrets
            ANON_KEY=$(openssl rand -hex 32)
            SERVICE_ROLE_KEY=$(openssl rand -hex 32)
            JWT_SECRET=$(openssl rand -hex 32)
            SECRET_KEY_BASE=$(openssl rand -hex 32)
            POSTGRES_PASSWORD=$(openssl rand -hex 16)

            cat > .env <<EOF
# Generated by manage.sh

# Supabase Keys
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres

# Auth
JWT_SECRET=${JWT_SECRET}
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# External Services (Leave blank or fill in)
OPENAI_API_KEY=
HUGGING_FACE_HUB_TOKEN=

# App
NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
EOF
        fi
    fi

    echo "Building and Starting Containers..."
    $DOCKER_COMPOSE_CMD up -d --build

    print_success "Stack is running!"
    echo "---------------------------------------------------"
    echo "Web App:        http://localhost:3000"
    echo "Supabase Studio: http://localhost:8001"
    echo "Supabase API:   http://localhost:8000"
    echo "---------------------------------------------------"
    echo "Logs: ./manage.sh logs"
    echo "Stop: ./manage.sh down"
}

function down() {
    print_header "Stopping Stack"
    $DOCKER_COMPOSE_CMD down
    print_success "Stack stopped."
}

function clean() {
    print_header "Cleaning Stack (Removing Volumes)"
    read -p "Are you sure you want to delete all database data? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        $DOCKER_COMPOSE_CMD down -v
        print_success "Stack stopped and volumes removed."
    else
        echo "Aborted."
    fi
}

function logs() {
    print_header "Streaming Logs"
    $DOCKER_COMPOSE_CMD logs -f
}

function init_db() {
    print_header "Initializing Database"

    echo "Waiting for database to be ready..."
    sleep 5

    # Apply Schema
    echo "Applying Schema..."
    # We use the db service to run psql
    # NOTE: The file path inside the container must match volume mount or we cat it
    # Since we didn't mount schema.sql in a way we can easily execute via CLI optionally without restarting,
    # let's rely on docker-compose exec to pipe it.

    docker-compose exec -T db psql -U postgres -d postgres < supabase/schema.sql

    # Apply Seed
    echo "Applying Seed Data..."
    docker-compose exec -T db psql -U postgres -d postgres < supabase/seed.sql

    print_success "Database initialized."
}

function help() {
    echo "Usage: ./manage.sh [command]"
    echo "Commands:"
    echo "  dev      - Start the full stack locally (Docker Compose)"
    echo "  init-db  - Apply schema and seed data to the database"
    echo "  down     - Stop the stack"
    echo "  clean    - Stop the stack and remove data volumes"
    echo "  logs     - Stream logs from all services"
    echo "  help     - Show this help message"
}

# Main Dispatch
case "$1" in
    dev)
        dev
        ;;
    down)
        down
        ;;
    clean)
        clean
        ;;
    logs)
        logs
        ;;
    init-db)
        init_db
        ;;
    *)
        if [ -z "$1" ]; then
            dev # Default to dev
        else
            help
        fi
        ;;
esac
